### PR TITLE
fix spork_8 enforcement without superblocks

### PR DESCRIPTION
**Pull request by alecthomas28**
It looks to me masternode payment enforcements are not being hit due to the superblock constants. This may be a way forward, but needs to be tested.

### CODE REVIEW

**Comment by tech1e** [comment]
Thank you @alecthomas28. What's your POLIS wallet address?

If this fixes the problem, you get 10 POLIS from me.

Others want to contribute to this great work? Support someone that's trying to patch the whole, instead of getting ripped by the cheeky miners?

**Comment by pulijalahari** [comment]
@alecthomas28 i will send 10 polis from my wallet. Please fix and also let me know if you want to guide me help you as i know good bit of java and can learn to help.

**Comment by CryptoRRT** [comment]
Fix this and I ll toss 5 polis sorry new node getting rewards stolen isnt helping me recover my losses

**Comment by alecthomas28** [comment]
Added some additional code to make this a bit cleaner.

**Comment by polispay** [comment]
Testing on testnet.

**Comment by tech1e** [comment]
Gents, your efforts on this are greatly appreciated.
As promised @alecthomas28, I've just transferred 10 POLIS to your address `PPrWrTomUZuZT6QoiRJUJh5Hf5tubpvoGt`

**Comment by polispay** [comment]
Reverted the commit, I open a develop branch to use this. Can you make pull request again?

**Pull request merged**
